version: '2'
services:
  app:
    build: ./service
    restart: always
    depends_on:
      - db
    ports:
      - 9000:9000
  db:
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 9001:${POSTGRES_PORT}
    volumes:
      - ./db/db-data:/var/lib/postgresql/data